### ISSUE TITLE
Image Rounded

### ISSUE THREAD

**Issue by pcm0nk** [antoniandre/vueper-slides#21]
Hi tnx for the component.
Im struggling to make the images rounded , I got :slideImageInside=true but now if i try to manipulate the css in my vue file it doesnt take effect and i dont even know if thats the right place im doing it 😄 would appreciate any help.
Thanks.

**Comment by antoniandre** [comment]
Hi @pcm0nk,

Sure, do you want to have only a rounded image (with some content) inside a rectangular slideshow, or the whole slideshow rounded?

**Comment by pcm0nk** [comment]
Thanks for the response @antoniandre 
the slideshow is rectangular itself but the pictures need to be rounded!
I have my :visible-slides=4 ,so 4 pictures(userpics) rounded with some content ( their name at the bottom).
Thanks for the help.

**Comment by antoniandre** [comment]
Hi @pcm0nk,

This is a way to do it (keeping the slideImageInside option):
<img width="1059" alt="screen shot 2019-01-05 at 16 22 56" src="https://user-images.githubusercontent.com/22971289/50720715-52e92d80-1106-11e9-9845-16bcfcd57279.png">

```css
.vueperslide {
    background: linear-gradient(15deg, #dde6ed, #5e89b2);
}

.vueperslide__image {
    /* Make the image rounded. */
    border-radius: 100px;

    /* Make the image scale from the slideshow height. width 0 & padding trick to keep image ratio */
    height: 60%;
    width: 0;
    padding-left: 20%;

    /* positioning at the center. */
    top: 10%;
    left: 50%;
    transform: translateX(-50%);
}

/* This is also needed but already done by vueper-slides: */
.vueperslide__image {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-size: cover;
}

.vueperslide__content-wrapper {
    top: 85%;
    left: 50%;
    transform: translateX(-50%);
    position: absolute;
}

/* Lastly your title styles. */
.vueperslide__title {
    font-size: 3em;
    opacity: .7;
    text-shadow: none;
    color: #376098;
}
```

Hope it helps!
