### ISSUE TITLE
Only Slide title at the Top, content at the bottom

### ISSUE THREAD

**Issue by Byloor** [antoniandre/vueper-slides#57]
Hi,

Can we have slide title outside as separate property. I want my slide content to be at the bottom and content to be at the Top. Is there anyway we can achieve this now?

I couldn't find it from the docs.

**Comment by antoniandre** [comment]
Hi @Byloor, This should be done via CSS from `slide-content-outside="top",` here is a demo for you:
https://codepen.io/antoniandre/pen/bGGzBEW

All you need is that:

```css
.vueperslide__content {
    text-align: center;
    position: absolute;
    top: 100%;
    margin-top: 0.5em;
    left: 0;
    right: 0;
    z-index: 2;
  }
```

Hope it helps.
